export const internships = [
  {
    title: "Backend разработчик",
    company: "Storytelling Software",
    focusOfInternship: "Backend developer",
    schedule: "Office",
    typeOfEmployment: "Partial",
    durationOfInternship: "5 месяцев",
    salary: "10000",
    skills: "Python, Mongo",
    conditions: "ООП, SOLID",
    isActive: "true",
    companyId: "661cf450dbfec467050470de",
  },
  {
    title: "Backend разработчик PHP",
    company: "Oggetto",
    focusOfInternship: "Backend developer",
    schedule: "Office",
    typeOfEmployment: "Full",
    durationOfInternship: "6 месяцев",
    salary: "10000",
    skills: "PHP, PostgreSQL",
    conditions: "PHP",
    isActive: "true",
    companyId: "661cfdc8a634e7c1c43e668d",
  },
  {
    title: "Frontend  React разработчик",
    company: "Storytelling Software",
    focusOfInternship: "Frontend developer",
    schedule: "Office",
    typeOfEmployment: "Partial",
    durationOfInternship: "4 месяца",
    salary: "10000",
    skills: "ReactJS, TypeScript",
    conditions: "JS, HTML, CSS, Git",
    isActive: "true",
    companyId: "661cf450dbfec467050470de",
  },
  {
    title: "Frontend Angular разработчик",
    company: "Dunice",
    focusOfInternship: "Frontend developer",
    schedule: "Office",
    typeOfEmployment: "Full",
    durationOfInternship: "5 месяцев",
    salary: "10000",
    skills: "AngularJS, TypeScript",
    conditions: "JS, HTML, CSS",
    isActive: "true",
    companyId: "660be15ee4ed82612c6296c5",
  },
  {
    title: "Frontend Vue разработчик",
    company: "Oggetto",
    focusOfInternship: "Frontend developer",
    schedule: "Office",
    typeOfEmployment: "Partial",
    durationOfInternship: "3 месяца",
    salary: "10000",
    skills: "Vue, TypeScript",
    conditions: "Vue, JS, HTML, CSS",
    isActive: "true",
    companyId: "661cfdc8a634e7c1c43e668d",
  },
  {
    title: "Frontend разработчик",
    company: "WebSailors",
    focusOfInternship: "Frontend developer",
    schedule: "Office",
    typeOfEmployment: "Full",
    durationOfInternship: "4 месяца",
    salary: "10000",
    skills: "React, Angular",
    conditions: "React, Angular, JS, HTML, CSS",
    isActive: "true",
    companyId: "66257d457d49900754d87f36",
  },
  {
    title: "UI/UX дизайнер",
    company: "Storytelling Software",
    focusOfInternship: "Designer",
    schedule: "Office",
    typeOfEmployment: "Partial",
    durationOfInternship: "3 месяца",
    salary: "15000",
    skills: "Figma",
    conditions: "Figma, основы композиции",
    isActive: "true",
    companyId: "661cf450dbfec467050470de",
  },
  {
    title: "UI/UX дизайнер",
    company: "Dunice",
    focusOfInternship: "Designer",
    schedule: "Office",
    typeOfEmployment: "Partial",
    durationOfInternship: "3 месяца",
    salary: "15000",
    skills: "Figma",
    conditions: "Figma, основы композиции",
    isActive: "true",
    companyId: "660be15ee4ed82612c6296c5",
  },
  {
    title: "UI дизайнер",
    company: "Oggetto",
    focusOfInternship: "Designer",
    schedule: "Office",
    typeOfEmployment: "Partial",
    durationOfInternship: "2 месяца",
    salary: "10000",
    skills: "Figma, Adobe Photoshop",
    conditions: "Figma, Adobe Photoshop, основы композиции",
    isActive: "true",
    companyId: "661cfdc8a634e7c1c43e668d",
  },
  {
    title: "Тестировщик веб-приложений",
    company: "Storytelling Software",
    focusOfInternship: "Teaster",
    schedule: "Office",
    typeOfEmployment: "Partial",
    durationOfInternship: "1 месяц",
    // salary: null,
    skills: "-",
    conditions: "-",
    isActive: "true",
    companyId: "661cf450dbfec467050470de",
  },
  {
    title: "Тестировщик веб-приложений",
    company: "Dunice",
    focusOfInternship: "Teaster",
    schedule: "Office",
    typeOfEmployment: "Partial",
    durationOfInternship: "1 месяц",
    // salary: null,
    skills: "-",
    conditions: "-",
    isActive: "true",
    companyId: "660be15ee4ed82612c6296c5",
  },
  {
    title: "Тестировщик игр",
    company: "Hobby Games",
    focusOfInternship: "Teaster",
    schedule: "Office",
    typeOfEmployment: "Partial",
    durationOfInternship: "2 месяца",
    salary: "5000",
    skills: "-",
    conditions: "-",
    isActive: "true",
    companyId: "66257d1a7d49900754d87f31",
  },
  {
    title: "Тестировщик веб-приложений",
    company: "Lachestry",
    focusOfInternship: "Teaster",
    schedule: "Office",
    typeOfEmployment: "Full",
    durationOfInternship: "1 месяц",
    // salary: null,
    skills: "-",
    conditions: "-",
    isActive: "true",
    companyId: "66257cec7d49900754d87f2c",
  },
  {
    title: "Мобильный разработчик",
    company: "Storytelling Software",
    focusOfInternship: "Mobile developer",
    schedule: "Office",
    typeOfEmployment: "Partial",
    durationOfInternship: "4 месяца",
    salary: "10000",
    skills: "Kotlin",
    conditions: "ООП",
    isActive: "true",
    companyId: "661cf450dbfec467050470de",
  },
  {
    title: "Мобильный разработчик",
    company: "Dunice",
    focusOfInternship: "Mobile developer",
    schedule: "Office",
    typeOfEmployment: "Full",
    durationOfInternship: "3 месяца",
    salary: "3000",
    skills: "Kotlin, Java",
    conditions: "ООП",
    isActive: "true",
    companyId: "660be15ee4ed82612c6296c5",
  },
  {
    title: "Менеджер",
    company: "Storytelling Software",
    focusOfInternship: "Manager",
    schedule: "Office",
    typeOfEmployment: "Full",
    durationOfInternship: "1 месяц",
    salary: "3000",
    skills: "-",
    conditions: "-",
    isActive: "true",
    companyId: "661cf450dbfec467050470de",
  },
  {
    title: "HR менеджер",
    company: "Storytelling Software",
    focusOfInternship: "Recruiter",
    schedule: "Office",
    typeOfEmployment: "Full",
    durationOfInternship: "1 месяц",
    salary: "3000",
    skills: "-",
    conditions: "-",
    isActive: "true",
    companyId: "661cf450dbfec467050470de",
  },
  {
    title: "HR менеджер",
    company: "Dunice",
    focusOfInternship: "Recruiter",
    schedule: "Office",
    typeOfEmployment: "Full",
    durationOfInternship: "1 месяц",
    salary: "3000",
    skills: "-",
    conditions: "-",
    isActive: "true",
    companyId: "660be15ee4ed82612c6296c5",
  },
  {
    title: "C++ разработчик",
    company: "НКБ ВС",
    focusOfInternship: "Other",
    schedule: "Office",
    typeOfEmployment: "Full",
    durationOfInternship: "5 месяцев",
    salary: "10000",
    skills: "ООП, SOLID",
    conditions: "ООП, SOLID",
    isActive: "true",
    companyId: "66257ec3ec3b9f9d0e39cc71",
  },
  {
    title: "Аналитик",
    company: "Lachestry",
    focusOfInternship: "Analyst",
    schedule: "Remotely",
    typeOfEmployment: "Full",
    durationOfInternship: "1 месяц",
    // salary: null,
    skills: "-",
    conditions: "-",
    isActive: "true",
    companyId: "66257cec7d49900754d87f2c",
  },
];
