export const internships = [
  {
    title: "Backend разработчик",
    company: "Storytelling Software",
    focusOfInternship: "Backend developer",
    schedule: "Office",
    typeOfEmployment: "Partial",
    durationOfInternship: "5 месяцев",
    salary: "8000",
    skills: "Python, MongoDB",
    conditions: "Понимание ООП, SOLID, умение решать алгоритмические задачи на базовом уровне",
    isActive: "true",
    companyId: "6646ffcced63de23bc714aa6",
  },
  {
    title: "Backend разработчик PHP",
    company: "Oggetto",
    focusOfInternship: "Backend developer",
    schedule: "Office",
    typeOfEmployment: "Full",
    durationOfInternship: "6 месяцев",
    salary: "10000",
    skills: "PHP, PostgreSQL, Magento",
    conditions: "Понимание ООП, SOLID, умение решать алгоритмические задачи на базовом уровне",
    isActive: "true",
    companyId: "664702035cdc5893c5d10147",
  },
  {
    title: "Frontend  React разработчик",
    company: "Storytelling Software",
    focusOfInternship: "Frontend developer",
    schedule: "Office",
    typeOfEmployment: "Partial",
    durationOfInternship: "4 месяца",
    salary: "10000",
    skills: "Опыт работы с React и Typescript, HTML, CSS, SCCS/LESS/SASS",
    conditions: "Понимание ООП, SOLID",
    isActive: "true",
    companyId: "6646ffcced63de23bc714aa6",
  },
  {
    title: "Frontend Angular разработчик",
    company: "Dunice",
    focusOfInternship: "Frontend developer",
    schedule: "Office",
    typeOfEmployment: "Full",
    durationOfInternship: "5 месяцев",
    salary: "10000",
    skills: "AngularJS, HTML, CSS",
    conditions: "Понимание ООП, опыт написания Unit-тестов",
    isActive: "true",
    companyId: "6647022b5cdc5893c5d1014c",
  },
  {
    title: "Frontend Vue разработчик",
    company: "Oggetto",
    focusOfInternship: "Frontend developer",
    schedule: "Office",
    typeOfEmployment: "Partial",
    durationOfInternship: "3 месяца",
    salary: "10000",
    skills: "Vue, TypeScript, JS, HTML, CSS",
    conditions: "Понимание ООП, SOLID, опыт написания Unit-тестов",
    isActive: "true",
    companyId: "664702035cdc5893c5d10147",
  },
  {
    title: "Frontend разработчик",
    company: "WebSailors",
    focusOfInternship: "Frontend developer",
    schedule: "Office",
    typeOfEmployment: "Full",
    durationOfInternship: "4 месяца",
    salary: "10000",
    skills: "React, Angular",
    conditions: "React, Angular, JS, HTML, CSS",
    isActive: "true",
    companyId: "664704775cdc5893c5d10151",
  },
  {
    title: "UI/UX дизайнер",
    company: "Storytelling Software",
    focusOfInternship: "Designer",
    schedule: "Office",
    typeOfEmployment: "Partial",
    durationOfInternship: "3 месяца",
    salary: "15000",
    skills: "Figma, Photoshop",
    conditions: "Figma, основы композиции",
    isActive: "true",
    companyId: "6646ffcced63de23bc714aa6",
  },
  {
    title: "UI/UX дизайнер",
    company: "Dunice",
    focusOfInternship: "Designer",
    schedule: "Office",
    typeOfEmployment: "Partial",
    durationOfInternship: "3 месяца",
    salary: "15000",
    skills: "Figma, Photoshop",
    conditions: "Figma, основы композиции",
    isActive: "true",
    companyId: "6647022b5cdc5893c5d1014c",
  },
  {
    title: "UI дизайнер",
    company: "Oggetto",
    focusOfInternship: "Designer",
    schedule: "Office",
    typeOfEmployment: "Partial",
    durationOfInternship: "2 месяца",
    salary: "10000",
    skills: "Figma, Adobe Photoshop",
    conditions: "Figma, Adobe Photoshop, основы композиции",
    isActive: "true",
    companyId: "664702035cdc5893c5d10147",
  },
  {
    title: "Тестировщик веб-приложений",
    company: "Storytelling Software",
    focusOfInternship: "Teaster",
    schedule: "Office",
    typeOfEmployment: "Partial",
    durationOfInternship: "1 месяц",
    // salary: null,
    skills: "-",
    conditions: "-",
    isActive: "true",
    companyId: "6646ffcced63de23bc714aa6",
  },
  {
    title: "Тестировщик веб-приложений",
    company: "Dunice",
    focusOfInternship: "Teaster",
    schedule: "Office",
    typeOfEmployment: "Partial",
    durationOfInternship: "1 месяц",
    // salary: null,
    skills: "Jest",
    conditions: "Владение теорией тестирования, умение писать авто-тесты, умение писать SQL-запросы",
    isActive: "true",
    companyId: "6647022b5cdc5893c5d1014c",
  },
  {
    title: "Тестировщик игр",
    company: "Hobby Games",
    focusOfInternship: "Teaster",
    schedule: "Office",
    typeOfEmployment: "Partial",
    durationOfInternship: "2 месяца",
    salary: "5000",
    skills: "-",
    conditions: "Владение теорией тестирования",
    isActive: "true",
    companyId: "6647049d5cdc5893c5d1015e",
  },
  {
    title: "Тестировщик веб-приложений",
    company: "Lachestry",
    focusOfInternship: "Teaster",
    schedule: "Office",
    typeOfEmployment: "Full",
    durationOfInternship: "1 месяц",
    // salary: null,
    skills: "Jest, SQL",
    conditions: "Владение теорией тестирования, умение писать авто-тесты, умение писать SQL-запросы",
    isActive: "true",
    companyId: "664704b65cdc5893c5d10163",
  },
  {
    title: "Мобильный разработчик",
    company: "Storytelling Software",
    focusOfInternship: "Mobile developer",
    schedule: "Office",
    typeOfEmployment: "Partial",
    durationOfInternship: "4 месяца",
    salary: "10000",
    skills: "Kotlin",
    conditions: "ООП",
    isActive: "true",
    companyId: "6646ffcced63de23bc714aa6",
  },
  {
    title: "Мобильный разработчик",
    company: "Dunice",
    focusOfInternship: "Mobile developer",
    schedule: "Office",
    typeOfEmployment: "Full",
    durationOfInternship: "3 месяца",
    salary: "3000",
    skills: "Kotlin, Java",
    conditions: "Понимание ООП, SOLID",
    isActive: "true",
    companyId: "6647022b5cdc5893c5d1014c",
  },
  {
    title: "Менеджер",
    company: "Storytelling Software",
    focusOfInternship: "Manager",
    schedule: "Office",
    typeOfEmployment: "Full",
    durationOfInternship: "1 месяц",
    salary: "3000",
    skills: "-",
    conditions: "-",
    isActive: "true",
    companyId: "6646ffcced63de23bc714aa6",
  },
  {
    title: "HR менеджер",
    company: "Storytelling Software",
    focusOfInternship: "Recruiter",
    schedule: "Office",
    typeOfEmployment: "Full",
    durationOfInternship: "1 месяц",
    salary: "3000",
    skills: "-",
    conditions: "-",
    isActive: "true",
    companyId: "6646ffcced63de23bc714aa6",
  },
  {
    title: "HR менеджер",
    company: "Dunice",
    focusOfInternship: "Recruiter",
    schedule: "Office",
    typeOfEmployment: "Full",
    durationOfInternship: "1 месяц",
    salary: "3000",
    skills: "-",
    conditions: "-",
    isActive: "true",
    companyId: "6647022b5cdc5893c5d1014c",
  },
  {
    title: "C++ разработчик",
    company: "НКБ ВС",
    focusOfInternship: "Other",
    schedule: "Office",
    typeOfEmployment: "Full",
    durationOfInternship: "5 месяцев",
    salary: "10000",
    skills: "ООП, SOLID",
    conditions: "ООП, SOLID",
    isActive: "true",
    companyId: "664704d65cdc5893c5d10168",
  },
  {
    title: "Аналитик",
    company: "Lachestry",
    focusOfInternship: "Analyst",
    schedule: "Remotely",
    typeOfEmployment: "Full",
    durationOfInternship: "1 месяц",
    // salary: null,
    skills: "-",
    conditions: "-",
    isActive: "true",
    companyId: "664704b65cdc5893c5d10163",
  },
];
